### ISSUE TITLE
cudnn.convert throws an error

### ISSUE THREAD

**Issue by rainforest1** [qureai/ultrasound-nerve-segmentation-using-torchnet#5]
Thank you for the code. When i try to train the model with th main.lua, i get the following error at cudnn.convert in machine.lua file. Please help

---

attempt to call method 'replace' (a nil value)
/<>/torch/install/bin/luajit: /<>/share/lua/5.1/cudnn/convert.lua:59: attempt to call method 'replace' (a nil value)
stack traceback:
    /<>/share/lua/5.1/cudnn/convert.lua:59: in function 'convert'
    /<>/torchnet-master/machine.lua:66: in function 'LoadModel'
    /<>/torchnet-master/machine.lua:36: in function '__init'
    /<>/lua/5.1/torch/init.lua:91: in function </<>share/lua/5.1/torch/init.lua:87>
    [C]: in function 'Machine'
    main.lua:54: in function 'main'
    main.lua:59: in main chunk
    [C]: in function 'dofile'
    ...plab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk

**Comment by chsasank** [comment]
May be update your installation of torch/nn/cudnn etc?

**Comment by shubhamjain0594** [comment]
Did it work?

**Comment by shubhamjain0594** [comment]
Closing because of no further comments.
