### ISSUE TITLE
how to modify to work on cpu

### ISSUE THREAD

**Issue by kirk86** [qureai/ultrasound-nerve-segmentation-using-torchnet#8]
hi i was wondering which are the critical parts which need modification in order to make it work on cpu?

thanks!

**Comment by shubhamjain0594** [comment]
Hi,

You will need to change cudnn.modules to nn.modules and remove any tensor = tensor:cuda() to as it is. This would be sufficient to make it work with CPU.

**Comment by kirk86** [comment]
@shubhamjain0594 thanks for the reply. I did change everything as suggested but now I'm getting a fatal error.

```
Setting up data loader using train/data.h5
Data loader setup done!
{
  savePath : "train/saved_models"
  valSize : 25
  dataset : "data"
  valDataset :
    {
      __dataset :
        {
          load : function: 0x16551280
          list : LongTensor - size: 1198
        }
      __replacement : false
      __perm : LongTensor - size: 25
      __size : 25
      __sampler : function: 0x164f9578
    }
  optimMethod : "sgd"
  valBatchSize : 32
  cvParam : 2
  maxepoch : 250
  trainSize : 100
  trainDataset :
    {
      __dataset :
        {
          load : function: 0x1636a7c8
          list : LongTensor - size: 4437
        }
      __replacement : false
      __perm : LongTensor - size: 100
      __size : 100
      __sampler : function: 0x1660c950
    }
  trainBatchSize : 64
  model : "models/unet.lua"
}
THREAD FATAL ERROR: could not create lua state
```

I think this might be related to file `machine.lua` in line `68`. You have something like:
`local criterion = cudnn.SpatialCrossEntropyCriterion(weights)`

but the spatial cross entropy criterion doesn't exist in the `nn` package. The closest that I could relate to is the `nn.SpatialClassNLLCriterion(weights)`, but I'm not sure if they could be translated at all in this way?

**Comment by kirk86** [comment]
@shubhamjain0594 thanks for your reply. I did the changes as you suggested but now I am facing the same issue as this [one](https://github.com/torch/torch7/issues/737)! Any ideas?

**Comment by shubhamjain0594** [comment]
Hey @kirk86, sorry for no replies. If possible let us know if it is solved?

**Comment by kirk86** [comment]
yeah thanks a lot I've managed to make it work on cpu so I'm closing this issue.
